### ISSUE TITLE
Player Fails to Load a Song after successful connection

### ISSUE THREAD

**Issue by Firedingo** [jbonjean/beluga-player#11]
So this just started happening and I can't see anything obvious to fix it. I press connect and wait, after a few moments it reports a successful connection, then the player attempts to fetch up a song only to be unsuccessful and returns back to the main screen while also reporting Unknown Error.
I looked a the log but couldn't see where the issue might be.

I used the HTML5 details tag to compress the log to make the issue neater.
<details>
<summary>The Log File, Just click to expand it open</summary>
`16:48:10 ERROR PlayerUI - cannotGetSourceDataLine
info.bonjean.beluga.exception.InternalException: cannotGetSourceDataLine
	at info.bonjean.beluga.player.SimpleAudioDevice.<init>(SimpleAudioDevice.java:63) ~[beluga-player-0.11.jar:0.11]
	at info.bonjean.beluga.player.MP3Player.play(MP3Player.java:105) ~[beluga-player-0.11.jar:0.11]
	at info.bonjean.beluga.gui.pivot.PlayerUI$Playback.run(PlayerUI.java:309) [beluga-player-0.11.jar:0.11]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_141]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
16:48:11 ERROR MainWindow - null
java.lang.NullPointerException
	at info.bonjean.beluga.gui.pivot.SongUI.initialize(SongUI.java:103) ~[beluga-player-0.11.jar:0.11]
	at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:587) ~[beluga-player-0.11.jar:0.11]
	at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:684) ~[beluga-player-0.11.jar:0.11]
	at info.bonjean.beluga.gui.pivot.MainWindow.loadPage(MainWindow.java:122) [beluga-player-0.11.jar:0.11]
	at info.bonjean.beluga.gui.pivot.UIController$26.run(UIController.java:869) [beluga-player-0.11.jar:0.11]
	at org.apache.pivot.wtk.ApplicationContext$QueuedCallback.run(ApplicationContext.java:1690) [beluga-player-0.11.jar:0.11]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_141]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_141]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_141]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_141]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_141]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_141]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_141]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_141]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_141]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_141]`
</details>

**Comment by jbonjean** [comment]
This looks like an issue with the sound device. What are your OS and JVM?

**Comment by Firedingo** [comment]
My OS is Windows 7 64-bit and my JVM is 1.8.0_141. Looks like I haven't updated it for a while.

**Comment by jbonjean** [comment]
So I tested on Windows 10 64 bit with Java 8u151 and the player is working properly. Sorry, this is the only Windows config I have, I cannot help you much.

**Comment by Firedingo** [comment]
That's fine. After you said sound device I went looking and I'm still not sure what happened but some how my sound card crashed while leaving the services functioning which I didn't realize initially. Restarting the services got the device going and a proper restart of my PC got things back to normal entirely.
It was really quite odd because I thought the player was having issues or maybe Pandora was but actually turned out to be my sound card which I hadn't expected based on what I could tell.
Thanks for replying. I'm guessing the issue is resolved now.
